### PR TITLE
Let's use black

### PR DESCRIPTION
**Pull request by JustKappaMan**
I think we should use [black](https://github.com/psf/black) as a formatter in this project. It's great and was integrated in PyCharm in last update.

### CODE REVIEW

**Comment by dyslexia** [comment]
@JustKappaMan Hey man! I had the same exact Idea! I added a linter and workflow. Want to approve?

https://github.com/x7finance/telegram-bot/pull/14

**Comment by JustKappaMan** [comment]
@Adz1DoubleD what do you think about it?

**Comment by Adz1DoubleD** [comment]
Definitely something we should lool at, I'm currently on vacation till August 4th

So will have a more in depth look then!

Thanks!

**Comment by JustKappaMan** [comment]
> I'm currently on vacation till August 4th
> 
> Thanks!

OK, thanks. Have a nice vacation 🍹

**Comment by Adz1DoubleD** [comment]
didn't approve the PR but did action

https://github.com/x7finance/telegram-bot/commit/9d147b28439979c08077d012c980950a1dd81d0a

thanks!

**Pull request closed without merging**
